/** Diablo IV — Lord of Hatred (Season 13) leveling point data */
window.D4_BUILDS = [
  {
    id: "warlock-dread-claws",
    name: "Dread Claws",
    className: "Warlock",
    tier: "A",
    tierLabel: "A-Tier · Solid All-Rounder",
    color: "#9b6fd4",
    icon: "warlock",
    playstyle: "Position Rampage inside packs for double Encircling Terror rings. Hellion Sting deletes bosses.",
    respecNote: "Stay on this build unless you want faster raw speed — then respec to Minion Warlock.",
    levels: [
      [1, "Hellion Sting", "Basic skill — generates Wrath"],
      [2, "Hellion Sting rank", "Keep pressure while unlocking core"],
      [3, "Dread Claws", "Core AoE — your main spender"],
      [4, "Nether Step", "Mobility + Shadowform for Encircling Terror"],
      [5, "Dread Claws rank"],
      [6, "Hellion Sting: Damage", "More single-target pressure"],
      [7, "Dread Claws rank"],
      [8, "Rampage", "Summon Greater Demon — Dominance bar", true],
      [9, "Hellion Sting: Eviscerate", "Boss/elite melter — lock your target!", true],
      [10, "Dread Claws: Ambush", "Stealth bonus applies to claws"],
      [11, "Nether Step: Movement Speed"],
      [12, "Rampage rank"],
      [13, "Dread Claws rank"],
      [14, "Hellion Sting: Tail Spikes", "Hold button to shred elites", true],
      [15, "★ Mastermind Soul Shard + Dread Claws: Encircling Terror", "Class quest + circular AoE", true],
      [16, "Sigil of Subversion", "Hex ritual — Shadowform trails"],
      [17, "Rampage rank"],
      [18, "Dread Claws rank"],
      [19, "Nether Step rank"],
      [20, "Rampage: Abyssal Titan", "Reposition demon without extra Dominance", true],
      [21, "Hellion Sting rank"],
      [22, "Dread Claws rank"],
      [23, "Sigil of Subversion rank"],
      [24, "Rampage rank"],
      [25, "Dread Claws: Cost Reduction"],
      [26, "Nether Step: Extra Charge"],
      [27, "Hellion Sting rank"],
      [28, "Dread Claws rank"],
      [29, "Sigil of Subversion rank"],
      [30, "★ Blasphemous Fragment", "Rampage applies Hex — second shard slot", true],
      [31, "Rampage rank"],
      [32, "Dread Claws rank"],
      [33, "Nether Step rank"],
      [34, "★ RESPEC: Command Fallen — Fallen Rush", "Drop Hellion Sting & Sigil. Tap 2–3× per 20s for Wrath", true],
      [35, "Dark Prison — Chain Aura", "Defensive aura package"],
      [36, "Command Fallen rank"],
      [37, "Dread Claws rank"],
      [38, "Rampage rank"],
      [39, "Nether Step: Recall Shadows", "Semi-auto reposition demon with Nether Step"],
      [40, "★ RESPEC: Metamorphosis — Terror Demon", "Drop Dark Prison. Shadowform + endgame scaling", true],
      [41, "Metamorphosis rank"],
      [42, "Dread Claws rank"],
      [43, "Command Fallen rank"],
      [44, "Metamorphosis rank"],
      [45, "Rampage rank"],
      [46, "Dread Claws rank"],
      [47, "Metamorphosis rank"],
      [48, "Command Fallen rank"],
      [49, "Dread Claws rank"],
      [50, "★ Capstone dungeon #2", "Unlock extra skill points", true],
      [51, "Metamorphosis rank"],
      [52, "Dread Claws rank"],
      [53, "Rampage rank"],
      [54, "Command Fallen rank"],
      [55, "Metamorphosis rank"],
      [56, "Dread Claws rank"],
      [57, "Nether Step rank"],
      [58, "Metamorphosis rank"],
      [59, "Dread Claws rank"],
      [60, "★ Clear Strongholds (Normal)", "One-time XP burst — then Penitent", true],
      [61, "Dread Claws rank"],
      [62, "Metamorphosis rank"],
      [63, "Rampage rank"],
      [64, "Command Fallen rank"],
      [65, "Dread Claws rank"],
      [66, "Metamorphosis rank"],
      [67, "Dread Claws rank"],
      [68, "Rampage rank"],
      [69, "Metamorphosis rank"],
      [70, "★ Pit Tier 10 → Torment 1", "Begin Paragon — see endgame Dread Claws guide", true],
    ],
    gear: ["Weapon first", "Vulnerable / Close damage tempers", "Accelerating · Edgemaster's · Deeper Shadows aspects"],
    runes: "Cir+Ceh (wolves/freeze) · Cem+Qua (move speed on evade)",
  },
  {
    id: "warlock-minion",
    name: "Minion Warlock",
    className: "Warlock",
    tier: "A",
    tierLabel: "A-Tier · Fastest Warlock Level",
    color: "#7c5cbf",
    icon: "warlock",
    playstyle: "Army of demons — safest and fastest Warlock level. Respec here if Dread Claws feels squishy.",
    respecNote: "Best Warlock pick for pure leveling speed. You lose Dread Claws AoE fantasy.",
    levels: mkLevels("Minion", [
      [1, "Hellion Sting"], [3, "Summon Hellhound"], [8, "Rampage"], [15, "★ Soul Shard quest"],
      [20, "Greater Demon variant"], [34, "Command Fallen"], [40, "Metamorphosis"], [50, "Capstone"], [60, "Strongholds"], [70, "Torment 1"],
    ]),
    gear: ["Minion damage · Attack speed", "Fortress · Insidious aspects"],
    runes: "Tam+Jah for spam and mobility",
  },
  {
    id: "rogue-dance-of-knives",
    name: "Dance of Knives",
    className: "Rogue",
    tier: "S",
    tierLabel: "S-Tier · Fastest Overall",
    color: "#5db87a",
    icon: "rogue",
    playstyle: "Spin through packs with insane clear. Best raw leveling in the game.",
    levels: mkLevels("DoK", [
      [1, "Blade Shift"], [2, "Dance of Knives"], [3, "Dark Shroud"], [5, "Blade Shift: Energy"],
      [7, "Dance of Knives: Star Shards"], [8, "Poison Imbuement"], [9, "Concealment"],
      [15, "★ Combo Points specialization"], [26, "Dance of Knives: Grenade Jumper"],
      [50, "Capstone"], [60, "Strongholds"], [70, "Torment 1"],
    ]),
    gear: ["Knife damage · Movement speed", "Accelerating · Rapid aspects"],
    runes: "Cem+Qua mobility",
  },
  {
    id: "rogue-twisting-blades",
    name: "Twisting Blades",
    className: "Rogue",
    tier: "S",
    tierLabel: "S-Tier · Armored Melee",
    color: "#4a9e6a",
    icon: "rogue",
    playstyle: "Tankier than Dance of Knives with excellent AoE blades.",
    levels: mkLevels("TB", [
      [1, "Blade Shift"], [2, "Twisting Blades"], [3, "Dark Shroud"], [15, "★ Specialization"],
      [50, "Capstone"], [60, "Strongholds"], [70, "Torment 1"],
    ]),
    gear: ["Blade damage · Damage reduction while spinning"],
    runes: "Cir+Ceh or Cem+Qua",
  },
  {
    id: "barb-frenzy-throw",
    name: "Frenzy Throw",
    className: "Barbarian",
    tier: "S",
    tierLabel: "S-Tier · Top Barb Level",
    color: "#e07830",
    icon: "barbarian",
    playstyle: "Ranged frenzy axes — huge damage and safe positioning.",
    levels: mkLevels("FT", [
      [1, "Frenzy"], [2, "Frenzy Throw"], [3, "Frenzy rank"], [7, "War Cry"],
      [15, "★ Masters of Battle"], [19, "Wrath of the Berserker"], [50, "Capstone"],
      [60, "Strongholds"], [70, "Torment 1"],
    ]),
    gear: ["Weapon damage · Frenzy ranks", "Edgemaster's · Accelerating"],
    runes: "Gar+Tam crit and core spam",
  },
  {
    id: "barb-whirlwind",
    name: "Whirlwind",
    className: "Barbarian",
    tier: "A",
    tierLabel: "A-Tier · Classic Spin",
    color: "#c45a20",
    icon: "barbarian",
    playstyle: "Classic spin-to-win. Slightly slower than Frenzy Throw but very smooth.",
    levels: mkLevels("WW", [
      [1, "Lunging Strike"], [2, "Whirlwind"], [7, "Challenging Shout"], [15, "★ Bursting Whirlwind"],
      [50, "Capstone"], [60, "Strongholds"], [70, "Torment 1"],
    ]),
    gear: ["Whirlwind ranks · Vulnerable"],
    runes: "Tam core spam",
  },
  {
    id: "sorc-blizzard",
    name: "Blizzard",
    className: "Sorcerer",
    tier: "S",
    tierLabel: "S-Tier · Safe AoE Mage",
    color: "#4a9fb8",
    icon: "sorcerer",
    playstyle: "Freeze and melt zones. Excellent season-start leveling.",
    levels: mkLevels("Bliz", [
      [1, "Arc Lash"], [2, "Frost Bolt"], [3, "Blizzard"], [7, "Teleport"], [8, "Ice Armor"],
      [15, "★ Legacy of the Magi"], [21, "Unstable Currents"], [50, "Capstone"],
      [60, "Strongholds"], [70, "Torment 1"],
    ]),
    gear: ["Blizzard ranks · Cold damage"],
    runes: "Cir+Ceh freeze synergy",
  },
  {
    id: "sorc-charged-bolts",
    name: "Charged Bolts",
    className: "Sorcerer",
    tier: "A",
    tierLabel: "A-Tier · Lightning Pivot",
    color: "#3d8aa3",
    icon: "sorcerer",
    playstyle: "Charged Bolts early → Ball Lightning pivot for speed.",
    levels: mkLevels("CB", [
      [1, "Arc Lash"], [2, "Charged Bolts"], [7, "Teleport"], [15, "★ Enchantment slot"],
      [39, "Ball Lightning pivot"], [50, "Capstone"], [60, "Strongholds"], [70, "Torment 1"],
    ]),
    gear: ["Lightning damage · Cast speed"],
    runes: "Tam+Jah",
  },
  {
    id: "necro-minion",
    name: "Minion Necro",
    className: "Necromancer",
    tier: "S",
    tierLabel: "S-Tier · Army Leveling",
    color: "#8b7fc9",
    icon: "necromancer",
    playstyle: "Skeleton/Reaper army — brain-dead easy, very fast.",
    levels: mkLevels("MN", [
      [1, "Bone Splinters"], [2, "Raise Skeleton"], [3, "Raise Skeleton rank"],
      [15, "★ Book of the Dead"], [22, "Corpse Explosion"], [50, "Capstone"],
      [60, "Strongholds"], [70, "Torment 1"],
    ]),
    gear: ["Minion damage · Minion attack speed"],
    runes: "Igni offerings if using shadows",
  },
  {
    id: "paladin-shield-retribution",
    name: "Shield of Retribution",
    className: "Paladin",
    tier: "S",
    tierLabel: "S-Tier · Fastest Paladin",
    color: "#d4af37",
    icon: "paladin",
    playstyle: "Shield bash retribution — top Paladin level speed.",
    levels: mkLevels("SoR", [
      [1, "Advance"], [2, "Shield Bash"], [3, "Defiance Aura"], [15, "★ Disciple Oath quest"],
      [25, "Arbiter of Justice"], [50, "Capstone"], [60, "Strongholds"], [70, "Torment 1"],
    ]),
    gear: ["Shield stats · Retribution damage"],
    runes: "Que defensive · Cem+Qua speed",
  },
  {
    id: "paladin-blessed-hammer",
    name: "Blessed Hammer",
    className: "Paladin",
    tier: "A",
    tierLabel: "A-Tier · Hammerdin",
    color: "#b8962e",
    icon: "paladin",
    playstyle: "Spinning hammers — iconic and strong through campaign.",
    levels: mkLevels("BH", [
      [1, "Advance"], [2, "Blessed Hammer"], [3, "Defiance Aura"], [12, "Falling Star"],
      [15, "★ Disciple Oath"], [18, "Condemn"], [50, "Capstone"], [60, "Strongholds"], [70, "Torment 1"],
    ]),
    gear: ["Hammer damage · Critical strike"],
    runes: "Cem+Qua",
  },
  {
    id: "druid-lightning-storm",
    name: "Lightning Storm",
    className: "Druid",
    tier: "A",
    tierLabel: "A-Tier · Best Druid Level",
    color: "#c4783a",
    icon: "druid",
    playstyle: "Permanent storm — great AoE and simple rotation.",
    levels: mkLevels("LS", [
      [1, "Wind Shear"], [2, "Lightning Storm"], [7, "Blood Howl"], [15, "★ Spirit boons"],
      [50, "Capstone"], [60, "Strongholds"], [70, "Torment 1"],
    ]),
    gear: ["Storm ranks · Lightning damage"],
    runes: "Tam spam",
  },
  {
    id: "spiritborn-crushing-hand",
    name: "Crushing Hand",
    className: "Spiritborn",
    tier: "A",
    tierLabel: "A-Tier · Best Spiritborn Level",
    color: "#3db88a",
    icon: "spiritborn",
    playstyle: "Spirit hand slams — top Spiritborn leveling pick.",
    levels: mkLevels("CH", [
      [1, "Thrash"], [2, "Crushing Hand"], [15, "★ Spirit system"], [50, "Capstone"],
      [60, "Strongholds"], [70, "Torment 1"],
    ]),
    gear: ["Hand damage · Spirit generation"],
    runes: "Cem+Qua",
  },
];

window.D4_TIER_LIST = {
  S: [
    { build: "rogue-dance-of-knives", note: "Fastest overall leveler" },
    { build: "barb-frenzy-throw", note: "Best Barbarian" },
    { build: "rogue-twisting-blades", note: "Tankier Rogue S-tier" },
    { build: "sorc-blizzard", note: "Safest caster" },
    { build: "necro-minion", note: "Easiest brain-dead army" },
    { build: "paladin-shield-retribution", note: "Fastest Paladin" },
  ],
  A: [
    { build: "warlock-dread-claws", note: "Your current build — great AoE" },
    { build: "warlock-minion", note: "Faster Warlock alternative" },
    { build: "barb-whirlwind", note: "Classic spin" },
    { build: "sorc-charged-bolts", note: "Lightning speed" },
    { build: "paladin-blessed-hammer", note: "Hammerdin" },
    { build: "druid-lightning-storm", note: "Best Druid" },
    { build: "spiritborn-crushing-hand", note: "Best Spiritborn" },
  ],
};

window.D4_STRATEGY = {
  phases: [
    {
      range: "1–50",
      title: "Campaign & Foundation",
      steps: [
        "Set difficulty to Normal (or Hard if cruising).",
        "Grab wardrobe pet for auto-loot.",
        "Travel to Nahantu Den — pick Mercenary (Varyana hired, Aldkin reinforcement for Warlock).",
        "Complete Lord of Hatred campaign on Normal for speed.",
        "Do NOT clear Strongholds yet — save one-time XP.",
        "Class mechanic unlocks at 15 (Warlock needs Soul Shard quest).",
        "First Capstone Dungeon ~45 for bonus skill points.",
      ],
    },
    {
      range: "50–60",
      title: "Helltide & Capstone",
      steps: [
        "Farm Helltides or Kurast Undercity.",
        "Second Capstone for more skill points + Pit unlock.",
        "Bump to Hard/Penitent when kills stay fast.",
      ],
    },
    {
      range: "60–70",
      title: "Strongholds & Torment",
      steps: [
        "Clear ALL Strongholds on Normal (huge XP).",
        "Temper, imprint, socket runes on rare gear.",
        "Push Pit to Tier 10 → unlock Torment 1.",
        "Capstones 3–5 through Paragon 75.",
      ],
    },
  ],
  respecAdvice: {
    "warlock-dread-claws": {
      stay: "Strong AoE, melts bosses with Hellion Sting until lvl 34 respec. Great all-rounder.",
      switch: "Minion Warlock if you want faster/safer leveling. Dance of Knives Rogue for absolute speed.",
      respecLevels: [34, 40],
    },
  },
};

/** Fill levels 1-70 between milestone anchors */
function mkLevels(prefix, milestones) {
  const map = new Map(milestones.map((m) => [m[0], m]));
  const primary = milestones.find((m) => m[1] && !m[1].startsWith("★"))?.[1] || `${prefix} Core`;
  const rows = [];
  for (let lvl = 1; lvl <= 70; lvl++) {
    if (map.has(lvl)) {
      const m = map.get(lvl);
      const skill = m[1];
      const note = m[2] || "";
      const isMilestone = skill.startsWith("★") || m[3];
      rows.push([lvl, skill, note, isMilestone]);
    } else {
      rows.push([lvl, `${primary} rank`, "Continue maxing priority skills"]);
    }
  }
  return rows;
}